config/routes.rb
Spree::Core::Engine.routes.draw do
  resources :questions, :only => [:show], :path => 'faq' do
    collection do
      get '(/page-:page)', :action => :index, :as => ''
      match '/browse/(*id)(/page-:page)', :action => :browse, :as => 'browse'
    end
  end
  
  namespace :admin do
    resources :questions do
      resources :taxons do
        member do
          get :select, :action => :select_for_question
          delete :remove, :action => :remove_for_question
        end
        collection do
          post :available, :action => :available_for_question
          get  :selected, :action => :selected_for_question
        end
      end
      resources :products do
        member do
          get :select, :action => :select_for_question
          delete :remove, :action => :remove_for_question
        end
        collection do
          post :available, :action => :available_for_question
          get  :selected, :action => :selected_for_question
        end
      end
    end
  end
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  has_and_belongs_to_many :questions, :join_table => 'spree_products_questions'
end

app/models/spree/question.rb
module Spree
  class Question < ActiveRecord::Base
    has_and_belongs_to_many :taxons, :join_table => 'spree_questions_taxons'
    has_and_belongs_to_many :products, :join_table => 'spree_products_questions'
    
    attr_accessible :question, :answer, :description
    
    paginates_per 10

    validates :question, :presence => true, :uniqueness => true
    validates :slug, :uniqueness => true
    validates_presence_of :answer

    before_validation do
      self.slug = question.to_s.to_url(:limit => 64) unless slug
    end
    
    def to_param
      slug
    end
      
      
  end
end

app/models/spree/taxon_decorator.rb
Spree::Taxon.class_eval do
  has_and_belongs_to_many :questions, :join_table => 'spree_questions_taxons'
end

app/controllers/spree/admin/products_decorator.rb
module Spree
  module Admin
    ProductsController.class_eval do
      def selected_for_question
        @question = load_question
        @products = @question.products

        respond_with(:admin, @products)
      end

      def available_for_question
        @question = load_question
        @products = params[:q].blank? ? [] : Spree::Product.where('lower(name) LIKE ?', "%#{params[:q].mb_chars.downcase}%")
        @products.delete_if { |product| @question.products.include?(product) }

        respond_with(:admin, @products)
      end

      def select_for_question
        @question = load_question
        @product = Product.find_by_permalink(params[:id])
        @question.products << @product
        @question.save
        @products = @question.products

        respond_with(:admin, @products)
      end

      def remove_for_question
        @question = load_question
        @product = Product.find_by_permalink(params[:id])
        @question.products.delete(@product)
        @question.save
        @products = @question.products

        respond_with(:admin, @product)
      end
    
      private
  
      def load_question
        Question.find_by_slug(params[:question_id])
      end
    end
  end
end

app/controllers/spree/admin/questions_controller.rb
module Spree
  module Admin
    class QuestionsController < ResourceController

      def index
        respond_with(@collection) do |format|
          format.html
          format.json { render :json => json_data }
        end
      end

      protected

      def find_resource
        Question.find_by_slug!(params[:id])
      end

      def collection
        return @collection if @collection.present?
        params[:q] ||= {}
        params[:q][:s] ||= "created_at desc"
        @search = Spree::Question.search(params[:q])
        @collection = @search.result.page(params[:page]).per(20)
      end
    end
  end
end

app/controllers/spree/admin/taxons_decorator.rb
module Spree
  module Admin
    TaxonsController.class_eval do
      def selected_for_question
        @question = load_question
        @taxons = @question.taxons

        respond_with(:admin, @taxons)
      end

      def available_for_question
        @question = load_question
        @taxons = params[:q].blank? ? [] : Spree::Taxon.where('lower(name) LIKE ?', "%#{params[:q].mb_chars.downcase}%")
        @taxons.delete_if { |taxon| @question.taxons.include?(taxon) }

        respond_with(:admin, @taxons)
      end

      def select_for_question
        @question = load_question
        @taxon = Taxon.find(params[:id])
        @question.taxons << @taxon
        @question.save
        @taxons = @question.taxons

        respond_with(:admin, @taxons)
      end

      def remove_for_question
        @question = load_question
        @taxon = Taxon.find(params[:id])
        @question.taxons.delete(@taxon)
        @question.save
        @taxons = @question.taxons

        respond_with(:admin, @taxon)
      end
    
      private
  
      def load_question
        Question.find_by_slug(params[:question_id])
      end
    end
  end
end

app/controllers/spree/questions_controller.rb
module Spree
  class QuestionsController < Spree::BaseController 

    def index
      @questions = Question.page(params[:page])
      raise ActionController::RoutingError.new('No Matching Questions') if not params[:page].nil? and @questions.all.empty?
      
      @title = 'Frequently Asked Questions'
      @canonical_url = questions_path(:page => (not params[:page].nil? and params[:page].to_i > 1 ? params[:page] : nil))
    end

    def browse
      @taxon = Taxon.find_by_permalink!(params[:id])
      @questions = @taxon.questions.page(params[:page])
      raise ActionController::RoutingError.new('No Matching Questions') if @questions.all.empty?

      @title = "#{@taxon.name} Frequently Asked Questions"

      render :index
    end
  
    def show
      @question = Question.find_by_slug!(params[:id])
      
      @title = @question.question
      @description = @question.description
      
      @canonical_url = question_path(@question)
    end
  end
end

app/views/spree/admin/products/_question_product_table.html.erb
<table class="index">
  <thead>
    <tr data-hook="products_header">
      <th><%= t(:name) %></th>
      <th><%= t(:path) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% products.each do |product| %>
      <tr id="<%= dom_id(product) %>" data-hook="products_row">
        <td><%= product.name %></td>
        <td><%= product_path product %></td>
        <td class="actions">
          <%= link_to_delete product, :url => remove_admin_question_product_url(@question, product), :name => icon('delete') + ' ' + t(:remove) %>
        </td>
      </tr>
    <% end %>
    <% if products.empty? %>
     <tr data-hook="products_none"><td colspan="3"><%= t(:none) %>.</td></tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/products/available_for_question.js.erb
<h4><%= t(:available_products) %></h4>
<table class="index">
  <thead>
    <tr>
      <th><%= t(:name) %></th>
      <th><%= t(:path) %></th>
      <th><%= t(:action) %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr id="<%= dom_id(product, :sel) %>">
        <td><%= product.name %></td>
        <td><%= product_path product %></td>
        <td class="actions">
          <%= link_to icon(:add) + ' ' + t(:select),
                            select_admin_question_product_path(@question, product),
                           :remote => true, :class => 'iconlink' %>
        </td>
      </tr>
    <% end %>
    <% if @products.empty? %>
     <tr><td colspan="3"><%= t(:no_match_found) %>.</td></tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/products/remove_for_question.js.erb
$("#selected-products").html("<%= escape_javascript(render(:partial => 'question_product_table', :locals => { :products => @products })) %>");

app/views/spree/admin/products/select_for_question.js.erb
$("#selected-products").html("<%= escape_javascript(render(:partial => 'question_product_table', :locals => { :products => @products })) %>");
$("#<%= dom_id @product, :sel %>").hide();

app/views/spree/admin/products/selected_for_question.html.erb
<%= render :partial => 'spree/admin/shared/question_tabs', :locals => { :current => 'Products' } %>
<div id="selected-products" data-hook>
  <%= render :partial => 'question_product_table', :locals => { :products => @products } %>
</div>

<%= form_tag '#' do %>
  <%= label_tag nil, t(:search) %>:
  <input id="searchtext" size="25">
<% end %>

<%= javascript_tag do %>
  function search_for_products(){
    $.ajax({
     data: {q: $("#searchtext").val() },
     dataType: 'html',
     success: function(request){
       jQuery('#search_hits').html(request);
     },
     type: 'POST',
     url: '<%= available_admin_question_products_url(@question, :format => 'js') %>'
    });
  }

  $("#searchtext").keypress(function (e) {
    if ((e.which && e.which == 13) || (e.keyCode && e.keyCode == 13)) {
      search_for_products();

      return false;
    } else {
       return true;
    }
  });

  $("#searchtext").delayedObserver(function() {
    search_for_products();
  }, 0.75);
<% end %>
<br />
<div id="search_hits" data-hook></div>

app/views/spree/admin/questions/_form.html.erb
<div class="clearfix">
  <div>
    <%= f.field_container :question do %>
      <%= f.label :question %> <span class="required">*</span><br />
      <%= f.text_field :question, :class => 'fullwidth title' %>
      <%= f.error_message_on :question %>
    <% end %>

    <%= f.field_container :description do %>
      <%= f.label :description %> <span class="required">*</span><br />
      <%= f.text_field :description, :class => 'fullwidth'%>
      <%= f.error_message_on :description %>
    <% end %>

    <%= f.field_container :answer do %>
      <%= f.label :answer %> <span class="required">*</span><br />
      <%= f.text_area :answer, {:class => 'fullwidth'} %>
      <%= f.error_message_on :answer %>
    <% end %>
  </div>
</div>

app/views/spree/admin/questions/edit.html.erb
<h1><%= t("editing_question") %></h1>
<%= render "spree/shared/error_messages", :target => @object %>

<%= render :partial => 'spree/admin/shared/question_tabs', :locals => { :current => 'Question Details' } %>

<%= form_for [:admin, @object] do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
<% end %>

app/views/spree/admin/questions/index.html.erb
<div class='toolbar'>
  <ul class='actions'>
    <li>
      <%= button_link_to 'New Question', new_object_url, { :icon => 'add' } %>
    </li>
  </ul>
  <br class='clear' />
</div>

<h1><%=t("questions") %></h1>

<table class="index">
  <tr>
    <th><%= Spree::Question.human_attribute_name(:question) %></th>
    <th><%= Spree::Question.human_attribute_name(:answer) %></th>
    <th><%= sort_link @search,:created_at, t(:created_at), { :default_order => "desc" }, {:title => 'admin_products_listing_created_at_title'} %></th>
    <th><%= t("action") %></th>
  </tr>
  <tbody>
      <% @questions.each do |question| %>
    <tr class="<%= cycle('even', 'odd') %>" id="<%= dom_id question %>">
      <td>
        <%= question.question %>
      </td>
      <td>
        <%= question.answer %>
      </td>
      <td style="white-space:nowrap;">
        <%= time_tag question.created_at, :format => '%B %e, %Y %l:%M %P' %>
      </td>
      <td style="white-space:nowrap;">
        <%= link_to_edit question %> &nbsp;
        <%= link_to_delete question %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @questions %>

<% content_for :sidebar do %>
  <div data-hook="admin_questions_sidebar">
    <%= search_form_for [:admin, @search] do |f| %>
      <div class="box">
        <h3><%= t(:search) %></h3>

        <%- locals = {:f => f} %>
        <div data-hook="admin_questions_index_search">
          <p>
            <%= f.label :question_cont, t(:question) %><br />
            <%= f.text_field :question_cont, :size => 40 %>
          </p>
          <p>
            <%= f.label :answer_cont, t(:answer) %><br />
            <%= f.text_field :answer_cont, :size => 40 %>
          </p>
        </div>

        <div data-hook="admin_questions_index_search_buttons">
          <p class="form-buttons">
            <%= button t(:search) %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/spree/admin/questions/new.html.erb
<h1><%= t(:editing_question) %></h1>
<%= render "spree/shared/error_messages", :target => @question %>

<%= form_for [:admin, @object] do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= render :partial => 'spree/admin/shared/new_resource_links' %>
<% end %>

app/views/spree/admin/shared/_question_tabs.html.erb
<h1><%= t(:editing_question) %> &ldquo;<%= @question.question %>&rdquo;</h1>

<% content_for :sidebar do %>

  <h3><%= @question.question %></h3>
  <br class="clear" />

  <ul class="sidebar question-menu" data-hook="admin_question_tabs">
    <li<%== ' class="active"' if current == 'Question Details' %>>
      <%= link_to t(:question_details), edit_admin_question_url(@question) %>
    </li>
    
    <li<%== ' class="active"' if current == 'Taxons' %>>
      <%= link_to t(:taxons), selected_admin_question_taxons_url(@question) %>
    </li>

    <li<%== ' class="active"' if current == 'Products' %>>
      <%= link_to t(:products), selected_admin_question_products_url(@question) %>
    </li>

  </ul>
  <br class="clear" />

<% end %>

app/views/spree/admin/taxons/_question_taxon_table.html.erb
<table class="index">
  <thead>
    <tr data-hook="taxons_header">
      <th><%= t(:name) %></th>
      <th><%= t(:path) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% taxons.each do |taxon| %>
      <tr id="<%= dom_id(taxon) %>" data-hook="taxons_row">
        <td><%= taxon.name %></td>
        <td><%= taxon_path taxon %></td>
        <td class="actions">
          <%= link_to_delete taxon, :url => remove_admin_question_taxon_url(@question, taxon), :name => icon('delete') + ' ' + t(:remove) %>
        </td>
      </tr>
    <% end %>
    <% if taxons.empty? %>
     <tr data-hook="taxons_none"><td colspan="3"><%= t(:none) %>.</td></tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/taxons/available_for_question.js.erb
<h4><%= t(:available_taxons) %></h4>
<table class="index">
  <thead>
    <tr>
      <th><%= t(:name) %></th>
      <th><%= t(:path) %></th>
      <th><%= t(:action) %></th>
    </tr>
  </thead>
  <tbody>
    <% @taxons.each do |taxon| %>
      <tr id="<%= dom_id(taxon, :sel) %>">
        <td><%= taxon.name %></td>
        <td><%= taxon_path taxon %></td>
        <td class="actions">
          <%= link_to icon(:add) + ' ' + t(:select),
                            select_admin_question_taxon_path(@question, taxon),
                           :remote => true, :class => 'iconlink' %>
        </td>
      </tr>
    <% end %>
    <% if @taxons.empty? %>
     <tr><td colspan="3"><%= t(:no_match_found) %>.</td></tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/taxons/remove_for_question.js.erb
$("#selected-taxons").html("<%= escape_javascript(render(:partial => 'question_taxon_table', :locals => { :taxons => @taxons })) %>");

app/views/spree/admin/taxons/select_for_question.js.erb
$("#selected-taxons").html("<%= escape_javascript(render(:partial => 'question_taxon_table', :locals => { :taxons => @taxons })) %>");
$("#<%= dom_id @taxon, :sel %>").hide();

app/views/spree/admin/taxons/selected_for_question.html.erb
<%= render :partial => 'spree/admin/shared/question_tabs', :locals => { :current => 'Taxons' } %>
<div id="selected-taxons" data-hook>
  <%= render :partial => 'question_taxon_table', :locals => { :taxons => @taxons } %>
</div>

<%= form_tag '#' do %>
  <%= label_tag nil, t(:search) %>:
  <input id="searchtext" size="25">
<% end %>

<%= javascript_tag do %>
  function search_for_taxons(){
    $.ajax({
     data: {q: $("#searchtext").val() },
     dataType: 'html',
     success: function(request){
       jQuery('#search_hits').html(request);
     },
     type: 'POST',
     url: '<%= available_admin_question_taxons_url(@question, :format => 'js') %>'
    });
  }

  $("#searchtext").keypress(function (e) {
    if ((e.which && e.which == 13) || (e.keyCode && e.keyCode == 13)) {
      search_for_taxons();

      return false;
    } else {
       return true;
    }
  });

  $("#searchtext").delayedObserver(function() {
    search_for_taxons();
  }, 0.75);
<% end %>
<br />
<div id="search_hits" data-hook></div>

app/views/spree/questions/index.html.haml
- content_for :sidebar do
  = render :partial => "spree/shared/faq_taxons"
- content_for :head do
  = auto_discovery_link_tag(:rss, spree.questions_path(:format => :xml, :page => nil), {:title => "FAQ Feed" })

%h1=@title

#questions_container
  - @questions.each do |question|
    = link_to question.question, question
    %br/
    = question.description
    %hr/
  =paginate @questions

app/views/spree/questions/show.html.haml
- content_for :sidebar do
  = render :partial => "spree/shared/faq_taxons"

%h1=@question.question
.answer=@question.answer.html_safe

- unless @question.products.all.empty?
  %hr
  %h2 Related Products
  %div{:data => {:hook => 'faq_products' } }
    = render :partial => 'spree/shared/products', :locals => { :products => @question.products }

- unless @question.taxons.all.empty?
  %hr
  %h2 Related Categories
  %ul
    - @question.taxons.each do |taxon|
      %li= link_to taxon.name, seo_url(taxon)

app/views/spree/shared/_faq_taxons.html.haml
- cache("faq_taxons", :expires_in => 1.hour) do
  %h5 Browse FAQ by Category
  %ul
    - Spree::Taxon.joins(:questions).group('spree_taxons.id').order(:position).find_each do |taxon|
      %li= link_to taxon.name, spree.browse_questions_path(:id => taxon.permalink)

app/views/spree/shared/_product_faq.html.haml
- if @product and not @product.questions.all.empty?
  .alpha.columns.five.omega
    %h6.product-section-title #{@product.name} FAQ
    %ul.products-faq
      - @product.questions.each do |question|
        %li=link_to question.question, question

app/views/spree/shared/_taxon_faq.html.erb
<% if @taxon and not @taxon.questions.limit(3).all.empty? %>
<div data-hook="taxon_sidebar_faq">
  <h6 class="taxonomy-root"><%=@taxon.name%> FAQ</h6>
  <ul class="taxons-list">
    <% @taxon.questions.limit(3).each do |question| %>
      <li><%=link_to question.question, question%></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/spree/shared/_taxon_faq.html.haml
- if @taxon && @taxon.questions
  %h6.taxonomy-root #{@taxon.name} FAQ
  %ul.taxons-list
    - @taxon.questions.each do |question|
      %li=link_to question.question, question